-- MySQL Script generated by MySQL Workbench
-- Fri Mar  2 16:46:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bolsadeempleo_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bolsadeempleo_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bolsadeempleo_schema` DEFAULT CHARACTER SET utf8 ;
USE `bolsadeempleo_schema` ;

-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `EmpresaNombre` VARCHAR(45) NOT NULL,
  `EmpresaLocalizacion` VARCHAR(45) NOT NULL,
  `EmpresaEmail` VARCHAR(45) NOT NULL,
  `EmpresaTelefono` VARCHAR(45) NOT NULL,
  `EmpresaDescripcion` VARCHAR(100) NOT NULL,
  `EmpresaClave` VARCHAR(45) NOT NULL,
  `EmpresaEstadoDeCuenta` VARCHAR(45) NOT NULL DEFAULT 'ESPERA',
  CONSTRAINT chk_EstadoEmpresa CHECK (`EmpresaEstadoDeCuenta` IN ('ESPERA', 'ACEPTADO', 'RECHAZADO')),
  CONSTRAINT pkempresa PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Nacionalidad` (
  `idNacionalidad` INT NOT NULL AUTO_INCREMENT,
  `NacionalidadNombre` VARCHAR(45) NOT NULL,
  CONSTRAINT pknacionalidad PRIMARY KEY (`idNacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Oferente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Oferente` (
  `idOferente` INT NOT NULL AUTO_INCREMENT,
  `OferenteCedula` VARCHAR(45) NOT NULL,
  `OferenteNombre` VARCHAR(45) NOT NULL,
  `OferenteApellido` VARCHAR(45) NOT NULL,
  `OferenteTelefono` VARCHAR(45) NOT NULL,
  `OferenteEmail` VARCHAR(45) NOT NULL,
  `OferenteResidencia` VARCHAR(45) NOT NULL,
  `OferenteCurriculum` BLOB NOT NULL,
  `Nacionalidad_idNacionalidad` INT NOT NULL,
  `OferenteEstadoDeCuenta` VARCHAR(45) NOT NULL DEFAULT 'ESPERA',
  `OferenteUserName` VARCHAR(45) NOT NULL,
  `OferenteClave` VARCHAR(45) NOT NULL,
  CONSTRAINT pkeoferente PRIMARY KEY (`idOferente`, `Nacionalidad_idNacionalidad`),
  INDEX `fk_Oferente_Nacionalidad_idx` (`Nacionalidad_idNacionalidad` ASC),
  CONSTRAINT chk_EstadoOferente CHECK (`OferenteEstadoDeCuenta` IN ('ESPERA', 'ACEPTADO', 'RECHAZADO')),
  CONSTRAINT `fk_Oferente_Nacionalidad`
    FOREIGN KEY (`Nacionalidad_idNacionalidad`)
    REFERENCES `bolsadeempleo_schema`.`Nacionalidad` (`idNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Habilidad` (
  `idHabilidad` INT NOT NULL AUTO_INCREMENT,
  `HabilidadNombre` VARCHAR(45) NOT NULL,
  `Habilidad_idHabilidad` INT NOT NULL,
  CONSTRAINT pkHabiidad PRIMARY KEY (`idHabilidad`, `Habilidad_idHabilidad`),
  INDEX `fk_Habilidad_Habilidad1_idx` (`Habilidad_idHabilidad` ASC),
  CONSTRAINT `fk_Habilidad_Habilidad1`
    FOREIGN KEY (`Habilidad_idHabilidad`)
    REFERENCES `bolsadeempleo_schema`.`Habilidad` (`idHabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `AdministradorUserName` VARCHAR(45) NOT NULL,
  `AdministradorClave` VARCHAR(45) NOT NULL,
  CONSTRAINT pkadministrador PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Puesto` (
  `idPuesto` INT NOT NULL AUTO_INCREMENT,
  `PuestoDescripcion` VARCHAR(1000) NOT NULL,
  `PuestoSalario` DOUBLE NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `PuestoActivo` TINYINT(1) NULL DEFAULT 1,
  CONSTRAINT pkpuesto PRIMARY KEY (`idPuesto`, `Empresa_idEmpresa`),
  INDEX `fk_Puesto_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  CONSTRAINT `fk_Puesto_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `bolsadeempleo_schema`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Puesto_has_Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Puesto_has_Habilidad` (
  `Puesto_idPuesto` INT NOT NULL,
  `Habilidad_idHabilidad` INT NOT NULL,
  `Porcentaje` TINYINT NULL,
  CONSTRAINT pk_Puesto_has_Habilidad_Habilidad PRIMARY KEY (`Puesto_idPuesto`, `Habilidad_idHabilidad`),
  INDEX `fk_Puesto_has_Habilidad_Habilidad1_idx` (`Habilidad_idHabilidad` ASC),
  INDEX `fk_Puesto_has_Habilidad_Puesto1_idx` (`Puesto_idPuesto` ASC),
  CONSTRAINT `fk_Puesto_has_Habilidad_Puesto1`
    FOREIGN KEY (`Puesto_idPuesto`)
    REFERENCES `bolsadeempleo_schema`.`Puesto` (`idPuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puesto_has_Habilidad_Habilidad1`
    FOREIGN KEY (`Habilidad_idHabilidad`)
    REFERENCES `bolsadeempleo_schema`.`Habilidad` (`idHabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsadeempleo_schema`.`Oferente_has_Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolsadeempleo_schema`.`Oferente_has_Habilidad` (
  `Oferente_idOferente` INT NOT NULL,
  `Habilidad_idHabilidad` INT NOT NULL,
  `Porcentaje` TINYINT NULL,
  CONSTRAINT pk_Oferente_has_Habilidad PRIMARY KEY (`Oferente_idOferente`, `Habilidad_idHabilidad`),
  INDEX `fk_Oferente_has_Habilidad_Habilidad1_idx` (`Habilidad_idHabilidad` ASC),
  INDEX `fk_Oferente_has_Habilidad_Oferente1_idx` (`Oferente_idOferente` ASC),
  CONSTRAINT `fk_Oferente_has_Habilidad_Oferente1`
    FOREIGN KEY (`Oferente_idOferente`)
    REFERENCES `bolsadeempleo_schema`.`Oferente` (`idOferente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferente_has_Habilidad_Habilidad1`
    FOREIGN KEY (`Habilidad_idHabilidad`)
    REFERENCES `bolsadeempleo_schema`.`Habilidad` (`idHabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
